pipeline{

agent none
stages{

    stage("build"){

        steps{

            script{

                echo "Building the app vraj"
            }
        }
    }
    stage("Deploy"){

        steps{

            script{

                echo "Deploying the app vraj"
            }
        }
    }
    }
}